/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nakagawa' at '15/05/01 13:40' with Gradle 2.3
 *
 * @author nakagawa, @date 15/05/01 13:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
